# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = ".dev/tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -v -o .dev/tmp/api ./cmd/http-api"
# Binary file yields from `cmd`.
bin = ".dev/tmp/api -l /var/log/simple-app/catalog.info.log -e /var/log/simple-app/catalog.error.log"
# Customize binary.
#full_bin = "./tmp/main"
# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html", "json"]
# Ignore these filename extensions or directories.
exclude_dir = ["assets", ".dev/tmp", "vendor", "frontend/node_modules","pg/data"]
# Watch these directories if you specified.
include_dir = []
# Exclude files.
exclude_file = []
# Exclude unchanged files.
exclude_unchanged = true
# This log file places in your tmp_dir.
log = "air.log"
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms
# Stop running old binary when build errors occur.
stop_on_error = true
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = true
# Delay after sending Interrupt signal
kill_delay = 100 # ms

[log]
# Show log time
time = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true